### ISSUE TITLE
Can I apply it to other environments?

### ISSUE THREAD

**Issue by qcgm1978** [winston/cactus#4]
Hello:
I want to know whether I can apply it like qunit, e.g. I include a js file and write test code.

I see the prerequisites in readme file as follows:

```
Ruby on Rails, 3.2.x
jquery-rails
```

Does it mean I can't apply it in other environments?

Best Regards

**Comment by winston** [comment]
Hi,

You can definitely use it without Rails. But you'll still need jQuery in your project.

So to get this working in other kinds of projects, you will need to:
- `gem install cactus` or copy `vendor/assets/javascripts/cactus.js` somewhere
- Include jQuery in your layout
- Add the following in the bottom of your layout
  
  <script src='<path/to>/cactus.js' type='text/javascript'></script>
  
  <script src='<path/to>/spec.js' type='text/javascript'></script>

If you have a number of spec files, include them according after `cactus.js`.

Hope this helps!

Thank you!

**Comment by qcgm1978** [comment]
Hello:
    Thanks a lot. It works directly referenced in html like the deom: http://jsbin.com/OpABeYa/3/edit?html,js,output

Best Regards
